### ISSUE TITLE
Need change dependency activesupport >= 2.2.2 but < 3.0.0

### ISSUE THREAD

**Issue by antono** [quirkey/gembox#11]
/usr/lib/ruby/1.8/rubygems.rb:280:in `activate': can't activate activesupport (= 2.3.5, runtime) for [], already activated activesupport-3.0.0.beta for ["gembox-0.2.1"] (Gem::LoadError)
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:35:in`require'
    from /var/lib/gems/1.8/gems/gembox-0.2.1/lib/gembox.rb:7
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /var/lib/gems/1.8/gems/gembox-0.2.1/bin/gembox:6
    from /var/lib/gems/1.8/bin/gembox:19:in `load'
    from /var/lib/gems/1.8/bin/gembox:19

**Comment by antono** [comment]
original issue was with missing mattr_reader in ActiveSuport 3.0.0

**Comment by antono** [comment]
$ sudo gem install rails --pre

$ gembox

/var/lib/gems/1.8/gems/mislav-will_paginate-2.3.11/lib/will_paginate/view_helpers.rb:37: undefined method `mattr_reader' for WillPaginate::ViewHelpers:Module (NoMethodError)
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /var/lib/gems/1.8/gems/gembox-0.2.1/lib/gembox.rb:10
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /var/lib/gems/1.8/gems/gembox-0.2.1/bin/gembox:6
    from /var/lib/gems/1.8/bin/gembox:19:in`load'
    from /var/lib/gems/1.8/bin/gembox:19

**Comment by ricpruss** [comment]
I am also still getting this even though it was claimed to be closed by https://github.com/quirkey/gembox/issues/closed#issue/13

**Comment by ches** [comment]
It seems that the issue is `require 'active_support'` loading ActiveSupport 3+ if it is installed. Changing the require in `lib/gembox.rb` to `require 'activesupport'` works for me.

**Comment by ches** [comment]
How about we just use ActiveSupport 3 and put this behind us?

https://github.com/quirkey/gembox/pull/14

There's also a fix in there for Gem::Dependency#version_requirements being gone in newer versions of rubygems, if anyone tracking this ticket is hitting that crasher.
