### ISSUE TITLE
doesn't work on windows

### ISSUE THREAD

**Issue by rdp** [quirkey/gembox#3]
Currently on doze...
installs ok
then vegas.rb needed "localhost" instead of "0.0.0.0"
then it resulted in a fork error.  Not sure if these are gembox things or not.
I might use your gembox code sometime for a separate site :)
Also you might want to link to info on gem server.
Cheers!
=-

**Comment by quirkey** [comment]
Hey rogerdpack - I just pushed an update that should fix the fork error. Could you install the latest vegas gem from github and let me know if that works? Thanks, --AQ

**Comment by rdp** [comment]
thanks for the update.

I did discover that running it in the foreground works in windows.
Patch available http://github.com/rogerdpack/vegas/tree/master
Cheers!
-=r

**Comment by rdp** [comment]
I take that back--same error on *nix

rdp@li49-39:~/installs/mbari_gembox_187/bin$ ./gembox
== Starting gembox
== Trying to start gembox on Port 5678
Unable to launch. No Browser application found.
Failure in opening http://0.0.0.0:5678 : Unable to find browser to launch for os family 'nix'.

as well as this error, even if I have webrick installed [I assume a sinatra error]
/home/rdp/installs/mbari_gembox_187/lib/ruby/gems/1.8/gems/sinatra-0.9.2/lib/sinatra/base.rb:930:in `detect_rack_handler': Server handler (thin,mongrel,webrick) not found. (RuntimeError)
        from /home/rdp/installs/mbari_gembox_187/lib/ruby/gems/1.8/gems/vegas-0.0.1/lib/vegas/runner.rb:17:in`send'

**Comment by rdp** [comment]
it does fork now in windows! sweet!
For some reason it now starts itself twice...and only works on the second time, and pulls up a browser window with a search for the word "child"...

C:\dev\ruby\gembox>ruby bin\gembox
[Tue Oct 20 12:01:43 -0600 2009] Running with Windows Settings
[Tue Oct 20 12:01:43 -0600 2009] Starting gembox
[Tue Oct 20 12:01:43 -0600 2009] Trying to start gembox on Port 5678

C:\dev\ruby\gembox>[Tue Oct 20 12:01:49 -0600 2009] Running with Windows Settings
[Tue Oct 20 12:01:49 -0600 2009] Starting gembox
[Tue Oct 20 12:01:49 -0600 2009] Trying to start gembox on Port 5678

**Comment by kowal** [comment]
After installing gembox on windows, I'm getting this:

```
C:\ruby_dev>gembox
[2011-02-12 12:29:53 +0100] Running with Windows Settings
[2011-02-12 12:29:53 +0100] Starting 'gembox'...
[2011-02-12 12:29:53 +0100] trying port 5678...
C:/Ruby192/lib/ruby/gems/1.9.1/gems/vegas-0.1.8/lib/vegas/runner.rb:187:in `daem
on': daemon() function is unimplemented on this machine (NotImplementedError)
```

Am i missing any gems on my machine?

```
C:\ruby_dev>gem list
*** LOCAL GEMS ***
activesupport (2.2.3)
gembox (0.2.3)
haml (2.0.10)
minitest (1.6.0)
rack (1.2.1)
rake (0.8.7)
rdoc (2.5.8, 2.4.3)
sinatra (1.1.2)
test-unit (2.1.2)
tilt (1.2.2)
vegas (0.1.8)
will_paginate (2.3.15)
win32-api (1.4.8 x86-mingw32)
win32-process (0.6.5)
windows-api (0.4.0)
windows-pr (1.1.3)
```
