### ISSUE TITLE
gembox doesn't works

### ISSUE THREAD

**Issue by tredoe** [quirkey/gembox#7]
Hi,

when I run 'gembox' I get the next failure:

```
/var/lib/gems/1.9.0/gems/activesupport-2.3.2/lib/active_support/core_ext/uri.rb:8:in `<top (required)>': uninitialized constant URI::Parser (NameError)
    from /var/lib/gems/1.9.0/gems/activesupport-2.3.2/lib/active_support/core_ext.rb:3:in `require'
    from /var/lib/gems/1.9.0/gems/activesupport-2.3.2/lib/active_support/core_ext.rb:3:in `block in <top (required)>'
    from /var/lib/gems/1.9.0/gems/activesupport-2.3.2/lib/active_support/core_ext.rb:1:in `each'
    from /var/lib/gems/1.9.0/gems/activesupport-2.3.2/lib/active_support/core_ext.rb:1:in `<top (required)>'
    from /var/lib/gems/1.9.0/gems/activesupport-2.3.2/lib/active_support.rb:55:in `require'
    from /var/lib/gems/1.9.0/gems/activesupport-2.3.2/lib/active_support.rb:55:in `<top (required)>'
    from /var/lib/gems/1.9.0/gems/gembox-0.1.5/lib/gembox.rb:7:in `require'
    from /var/lib/gems/1.9.0/gems/gembox-0.1.5/lib/gembox.rb:7:in `<top (required)>'
    from /var/lib/gems/1.9.0/gems/gembox-0.1.5/bin/gembox:6:in `require'
    from /var/lib/gems/1.9.0/gems/gembox-0.1.5/bin/gembox:6:in `<top (required)>'
    from ./gembox:19:in `load'
    from ./gembox:19:in `<main>'
```

**Comment by quirkey** [comment]
Hey kless,

Unfortunately Ruby 1.9.0 isnt supported by ActiveSupport (one of the dependencies of gembox). See more info here: http://www.bluequartz.us/phpBB2/viewtopic.php?t=88994&sid=7e8d80d8a18e0a086fdf58809608be8b 

It should work fine on Ruby 1.9.1

--AQ
